function [endo, epi] = samplingBC(ImCrop, endo_c,epi_c,samplen)
%%% the sampling will based on the centre point from endo_c
endo_c = double(endo_c);
epi_c = double(epi_c);

k_endo = convhull(endo_c(1,:),endo_c(2,:));
k_epi = convhull(epi_c(1,:),epi_c(2,:));

endo_conv(1,:)=endo_c(1,k_endo);
endo_conv(2,:)=endo_c(2,k_endo);

epi_conv(1,:)=epi_c(1,k_epi);
epi_conv(2,:)=epi_c(2,k_epi);

%%centre point based on endo
shapex = sum(endo_c(1,:))/length(endo_c(1,:));
shapey = sum(endo_c(2,:))/length(endo_c(2,:));

endo_deg = [];
for i = 1 : length(endo_conv(1,:))
      dx=endo_conv(1,i)-shapex;
      dy=endo_conv(2,i)-shapey;
      
      if dx>=0 & dy==0
          endo_deg(i)=0;
      elseif dx>0 & dy<0
          endo_deg(i) = atan(abs(dy/dx));
      elseif dx==0 & dy>0
          endo_deg(i) = pi/2;
      elseif dx<0 & dy<0
          endo_deg(i) = pi-atan(abs(dy/dx));
      elseif dx<0 & dy==0
          endo_deg(i)=pi;
      elseif dx<0 & dy>0
          endo_deg(i)=pi+atan(abs(dy/dx));
      elseif dx==0 & dy>0
          endo_deg(i)=1.5*pi;
      elseif dx>0 & dy>0
          endo_deg(i)=2*pi-atan(abs(dy/dx));
      else
          endo_deg(i)=0;
      end
end
          

epi_deg = [];
for i = 1 : length(epi_conv(1,:))
      dx=epi_conv(1,i)-shapex;
      dy=epi_conv(2,i)-shapey;
      
      if dx>=0 & dy==0
          epi_deg(i)=0;
      elseif dx>0 & dy<0
          epi_deg(i) = atan(abs(dy/dx));
      elseif dx==0 & dy>0
          epi_deg(i) = pi/2;
      elseif dx<0 & dy<0
          epi_deg(i) = pi-atan(abs(dy/dx));
      elseif dx<0 & dy==0
          epi_deg(i)=pi;
      elseif dx<0 & dy>0
          epi_deg(i)=pi+atan(abs(dy/dx));
      elseif dx==0 & dy>0
          epi_deg(i)=1.5*pi;
      elseif dx>0 & dy>0
          epi_deg(i)=2*pi-atan(abs(dy/dx));
      else
          epi_deg(i)=0;
      end
end

% imshow(ImCrop,[]);hold on;
% plot(shapex,shapey,'r*');hold on;
% plot(shapex-50,0,'r*');
% plot(100,0,'r*');

%%%% sort the bc according to the degree
[endo_deg_s_t endo_index_s]=sort(endo_deg);
endo_sorted_t(1,:)=endo_conv(1,endo_index_s);
endo_sorted_t(2,:)=endo_conv(2,endo_index_s);
%%unique the data
index_k = 1;
for i = 1 : length(endo_deg_s_t)
      if endo_deg_s_t(i)>=0
          for j = i+1: length(endo_deg_s_t)
              if endo_deg_s_t(i)==endo_deg_s_t(j)
                  endo_deg_s_t(j)=-10;
              end
          end
          endo_deg_s(index_k)=endo_deg_s_t(i);
          endo_sorted(1,index_k)=endo_sorted_t(1,i);
          endo_sorted(2,index_k)=endo_sorted_t(2,i);
          index_k=index_k+1;
      end
end


[epi_deg_s_t epi_index_s]=sort(epi_deg);
epi_sorted_t(1,:)=epi_conv(1,epi_index_s);
epi_sorted_t(2,:)=epi_conv(2,epi_index_s);
index_k = 1;
for i = 1 : length(epi_deg_s_t)
      if epi_deg_s_t(i)>=0
          for j = i+1: length(epi_deg_s_t)
              if epi_deg_s_t(i)==epi_deg_s_t(j)
                  epi_deg_s_t(j)=-10;
              end
          end
          epi_deg_s(index_k)=epi_deg_s_t(i);
          epi_sorted(1,index_k)=epi_sorted_t(1,i);
          epi_sorted(2,index_k)=epi_sorted_t(2,i);
          index_k=index_k+1;
      end
end


%%% according samplen, the new boundary will be generated by spline
endo_sorted_1(1,:)=[endo_sorted(1,end) endo_sorted(1,:) endo_sorted(1,1)];
endo_sorted_1(2,:)=[endo_sorted(2,end) endo_sorted(2,:) endo_sorted(2,1)];
endo_deg_s_1=[endo_deg_s(end)-2*pi endo_deg_s endo_deg_s(1)+2*pi];

newDegree=0:2*pi/samplen:2*pi-2*pi/samplen;
endo_sampled(1,:)=spline(endo_deg_s_1,endo_sorted_1(1,:),newDegree);
endo_sampled(2,:)=spline(endo_deg_s_1,endo_sorted_1(2,:),newDegree);


epi_sorted_1(1,:)=[epi_sorted(1,end) epi_sorted(1,:) epi_sorted(1,1)];
epi_sorted_1(2,:)=[epi_sorted(2,end) epi_sorted(2,:) epi_sorted(2,1)];
epi_deg_s_1=[epi_deg_s(end)-2*pi epi_deg_s epi_deg_s(1)+2*pi];

newDegree=0:2*pi/samplen:2*pi-2*pi/samplen;
epi_sampled(1,:)=spline(epi_deg_s_1,epi_sorted_1(1,:),newDegree);
epi_sampled(2,:)=spline(epi_deg_s_1,epi_sorted_1(2,:),newDegree);



% imshow(ImCrop,[]);hold on;
% plot(shapex,shapey,'r*');hold on;
% for i = 1 : length(endo_sampled(1,:))
%     pause(0.1);hold on;
%     plot(endo_sampled(1,i),endo_sampled(2,i),'r.');
%     plot(epi_sampled(1,i),epi_sampled(2,i),'b.');
% end
% plot(endo_sorted_1(1,1),endo_sorted_1(2,1),'r*');



endo=endo_sampled;
epi = epi_sampled;

